#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

newstr="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/bagwuel permanent;"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i "s/server_name _;/$newstr/" /etc/nginx/sites-enabled/default

sudo service nginx start
