#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx

newstr="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = 404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$newstr/" /etc/nginx/sites-enabled/default

sudo service nginx restart
