#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

lines="\nfrontend my_frontend\n\tbind *:80\n\tdefault_backend alx_backend\n\nbackend alx_backend\n\tbalance roundrobin\n\tserver 339677-web-01 18.207.236.32:80 check\n\tserver 339677-web-02 52.201.228.254:80 check"

sudo echo -e $lines >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
