#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 100.25.158.171
    HostName 100.25.158.171
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
